#include "config_loader.h"
#include <fstream>
#include <sstream>
#include <cstdlib>

ConfigLoader::ConfigLoader(const std::string &path) : configPath(path) {}

bool ConfigLoader::load()
{
    std::lock_guard<std::mutex> lock(configMutex);
    std::ifstream file(configPath);
    if (!file.is_open())
        return false;

    std::stringstream buffer;
    buffer << file.rdbuf();
    std::string content = buffer.str();
    file.close();

    if (configPath.find(".json") != std::string::npos)
    {
        parseJSON(content);
    }
    else
    {
        parseINI(content);
    }
    return true;
}

void ConfigLoader::parseLine(const std::string &line)
{
    if (line.empty() || line[0] == '#' || line[0] == ';')
        return;

    size_t eqPos = line.find('=');
    if (eqPos == std::string::npos)
        return;

    std::string key = line.substr(0, eqPos);
    std::string value = line.substr(eqPos + 1);

    while (!key.empty() && key.back() == ' ')
        key.pop_back();
    while (!key.empty() && key.front() == ' ')
        key.erase(0, 1);
    while (!value.empty() && value.back() == ' ')
        value.pop_back();
    while (!value.empty() && value.front() == ' ')
        value.erase(0, 1);

    if (value.size() >= 2 && value.front() == '"' && value.back() == '"')
    {
        value = value.substr(1, value.size() - 2);
    }

    config[key] = value;
}

void ConfigLoader::parseJSON(const std::string &content)
{
}

void ConfigLoader::parseINI(const std::string &content)
{
    std::stringstream ss(content);
    std::string line;
    while (std::getline(ss, line))
    {
        parseLine(line);
    }
}

bool ConfigLoader::save()
{
    std::lock_guard<std::mutex> lock(configMutex);
    std::ofstream file(configPath);
    if (!file.is_open())
        return false;

    file << "# Configuration File\n";
    file << "# Generated by Banking System\n\n";

    for (const auto &[key, value] : config)
    {
        file << key << " = " << value << "\n";
    }

    file.close();
    return true;
}

bool ConfigLoader::reload()
{
    return load();
}

std::string ConfigLoader::getString(const std::string &key, const std::string &defaultValue) const
{
    std::lock_guard<std::mutex> lock(configMutex);
    auto it = config.find(key);
    if (it != config.end())
        return it->second;
    return defaultValue;
}

int ConfigLoader::getInt(const std::string &key, int defaultValue) const
{
    std::string val = getString(key, "");
    if (val.empty())
        return defaultValue;
    try
    {
        return std::stoi(val);
    }
    catch (...)
    {
        return defaultValue;
    }
}

double ConfigLoader::getDouble(const std::string &key, double defaultValue) const
{
    std::string val = getString(key, "");
    if (val.empty())
        return defaultValue;
    try
    {
        return std::stod(val);
    }
    catch (...)
    {
        return defaultValue;
    }
}

bool ConfigLoader::getBool(const std::string &key, bool defaultValue) const
{
    std::string val = getString(key, "");
    if (val.empty())
        return defaultValue;
    return val == "true" || val == "1" || val == "yes" || val == "on";
}

void ConfigLoader::setString(const std::string &key, const std::string &value)
{
    std::lock_guard<std::mutex> lock(configMutex);
    config[key] = value;
}

void ConfigLoader::setInt(const std::string &key, int value)
{
    setString(key, std::to_string(value));
}

void ConfigLoader::setDouble(const std::string &key, double value)
{
    setString(key, std::to_string(value));
}

void ConfigLoader::setBool(const std::string &key, bool value)
{
    setString(key, value ? "true" : "false");
}

bool ConfigLoader::hasKey(const std::string &key) const
{
    std::lock_guard<std::mutex> lock(configMutex);
    return config.find(key) != config.end();
}

void ConfigLoader::removeKey(const std::string &key)
{
    std::lock_guard<std::mutex> lock(configMutex);
    config.erase(key);
}

std::vector<std::string> ConfigLoader::getKeys() const
{
    std::lock_guard<std::mutex> lock(configMutex);
    std::vector<std::string> keys;
    for (const auto &[key, _] : config)
    {
        keys.push_back(key);
    }
    return keys;
}

void ConfigLoader::clear()
{
    std::lock_guard<std::mutex> lock(configMutex);
    config.clear();
}

std::string EnvironmentConfig::getEnv(const std::string &name, const std::string &defaultValue)
{
    const char *val = std::getenv(name.c_str());
    if (val)
        return std::string(val);
    return defaultValue;
}

int EnvironmentConfig::getEnvInt(const std::string &name, int defaultValue)
{
    std::string val = getEnv(name, "");
    if (val.empty())
        return defaultValue;
    try
    {
        return std::stoi(val);
    }
    catch (...)
    {
        return defaultValue;
    }
}

bool EnvironmentConfig::getEnvBool(const std::string &name, bool defaultValue)
{
    std::string val = getEnv(name, "");
    if (val.empty())
        return defaultValue;
    return val == "true" || val == "1" || val == "yes" || val == "on";
}

void EnvironmentConfig::setEnv(const std::string &name, const std::string &value)
{
#ifdef _WIN32
    _putenv_s(name.c_str(), value.c_str());
#else
    setenv(name.c_str(), value.c_str(), 1);
#endif
}
