#ifndef BANK_CONFIG_H
#define BANK_CONFIG_H

#define BANK_VERSION_MAJOR 3
#define BANK_VERSION_MINOR 0
#define BANK_VERSION_PATCH 0

#define BANK_USE_AES_NI 1
#define BANK_USE_AVX2 0
#define BANK_USE_SSE4 1

#define BANK_THREAD_SAFE 1
#define BANK_ZEROIZE_MEMORY 1
#define BANK_CANARY_PROTECTION 1

#define BANK_MAX_PASSWORD_LEN 4096
#define BANK_MIN_PBKDF2_ROUNDS 100000
#define BANK_MAX_PBKDF2_ROUNDS 10000000

#define BANK_SESSION_AUTO_CLEANUP 1
#define BANK_SESSION_CLEANUP_INTERVAL 60
#define BANK_DEFAULT_SESSION_TTL 3600

#define BANK_ENABLE_SELF_TEST 1
#define BANK_ENABLE_STATS 1
#define BANK_ENABLE_LOGGING 1

#define BANK_CRYPTO_SECURE 1

#endif
